# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_UNSPLASH_ACCESS_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
